// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXqEw0WvjfBHnPOhnnsRup-Joi6464Xmw',
    appId: '1:962784303234:web:266d33ff52c69380163c9b',
    messagingSenderId: '962784303234',
    projectId: 'fireflutter-site',
    authDomain: 'fireflutter-site.firebaseapp.com',
    databaseURL: 'https://fireflutter-site-default-rtdb.firebaseio.com',
    storageBucket: 'fireflutter-site.appspot.com',
    measurementId: 'G-MNTN8S7JCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJp-RDHiqT4OWdCI5JqrH8pFeeFA-uBmQ',
    appId: '1:962784303234:android:b38e1b1d84a65bdf163c9b',
    messagingSenderId: '962784303234',
    projectId: 'fireflutter-site',
    databaseURL: 'https://fireflutter-site-default-rtdb.firebaseio.com',
    storageBucket: 'fireflutter-site.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgqOdZsPOIr2Y0BwzBNg-IAptE-_oI81o',
    appId: '1:962784303234:ios:bdae9dd09e7a285d163c9b',
    messagingSenderId: '962784303234',
    projectId: 'fireflutter-site',
    databaseURL: 'https://fireflutter-site-default-rtdb.firebaseio.com',
    storageBucket: 'fireflutter-site.appspot.com',
    iosClientId: '962784303234-rfl95rh8ugj7hgv083vjba852a5n3vnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireflutterSite',
  );
}
